name: Deploy to Google GKE

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to Docker Hub
      id: build-image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $DOCKERHUB_USERNAME/python-flask-web:$IMAGE_TAG .
        docker push $DOCKERHUB_USERNAME/python-flask-web:$IMAGE_TAG
        echo "image=$DOCKERHUB_USERNAME/python-flask-web:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.3' # Specify your desired kubectl version

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install gke-gcloud-auth-plugin
      id: install_gke_gcloud_auth_plugin
      run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update
          sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
        
    - name: Update kube config
      run: gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }}
        
    - name: Deploy to GKE
      run: |
        sed -i 's|__IMAGE_URL__|${{ steps.build-image.outputs.image }}|g' k8s/deployment.yml
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml

    - name: Wait for deployment to complete
      run: kubectl rollout status deployment/python-flask-web-deployment --timeout=300s

    - name: Get Load Balancer IP
      run: |
        echo "Waiting for Load Balancer to be provisioned..."
        sleep 30
        kubectl get svc python-flask-web-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}' > load_balancer_ip.txt
        echo "Load Balancer IP: $(cat load_balancer_ip.txt)"
